#!/bin/sh
# Regenerates lib/build_config.mbt (gitignored) from flavors.tsv: CETAS_FLAVOR
# picks the table column (default personal), CETAS_PLATFORM the target OS
# (default: build host). Runs with the cetas-core module root as cwd.
set -eu

table=flavors.tsv
out=lib/build_config.mbt

flavor=${CETAS_FLAVOR-personal}
case "$flavor" in
  public | personal) ;;
  *)
    echo "gen-build-config: CETAS_FLAVOR must be public or personal (got '$flavor')" >&2
    exit 2
    ;;
esac

if [ "${CETAS_PLATFORM+set}" = set ]; then
  platform=$CETAS_PLATFORM
  case "$platform" in
    windows | unix) ;;
    *)
      echo "gen-build-config: CETAS_PLATFORM must be windows or unix (got '$platform')" >&2
      exit 2
      ;;
  esac
else
  case "$(uname -s)" in
    MINGW* | MSYS* | CYGWIN* | Windows*) platform=windows ;;
    *) platform=unix ;;
  esac
fi

column=$(awk -F '\t' -v want="$flavor" '/^#/ { for (i = 2; i <= NF; i++) if ($i == want) { print i; exit } }' "$table")
[ -n "$column" ] || {
  echo "gen-build-config: no '$flavor' column in $table" >&2
  exit 2
}

value_of() {
  awk -F '\t' -v ext="$1" -v col="$column" '!/^#/ && $1 == ext { print $col; exit }' "$table"
}

flag() {
  case "$1" in
    0) echo false ;;
    1) echo true ;;
    *)
      echo "gen-build-config: bad value '$1' for $2 in $table (need 0|1)" >&2
      exit 2
      ;;
  esac
}

nmem=$(flag "$(value_of nmem)" nmem)
obsidian=$(flag "$(value_of obsidian)" obsidian)
rtk=$(flag "$(value_of rtk)" rtk)

mkdir -p lib
cat > "$out" <<EOF
///|
/// GENERATED by scripts/gen-build-config.sh from flavors.tsv - do not edit, not tracked.
/// flavor=$flavor platform=$platform
fn compiled_nmem_enabled() -> Bool { $nmem }

///|
fn compiled_obsidian_enabled() -> Bool { $obsidian }

///|
fn compiled_rtk_enabled() -> Bool { $rtk }

///|
fn compiled_target_os() -> String { "$platform" }
EOF
